#!/usr/bin/env python3
"""Regenerate releases.js from the Spotify catalogue for овощ.

Usage:
    export SPOTIFY_CLIENT_ID=...        # from developer.spotify.com/dashboard
    export SPOTIFY_CLIENT_SECRET=...
    python3 tools/update_releases.py

Standard library only. Writes releases.js in the repository root.
"""

import base64
import json
import os
import pathlib
import sys
import urllib.parse
import urllib.request

ARTIST_ID = "1K7Bggsg4Zgv6ecC0iQhsl"  # овощ
OUT = pathlib.Path(__file__).resolve().parent.parent / "releases.js"

HEADER = """/* Generated by tools/update_releases.py — do not edit by hand.
 * Every release by овощ on Spotify, newest first.
 */

window.RELEASES = [
"""


def get(url, token):
    request = urllib.request.Request(url, headers={"Authorization": "Bearer " + token})
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def token():
    client_id = os.environ.get("SPOTIFY_CLIENT_ID")
    secret = os.environ.get("SPOTIFY_CLIENT_SECRET")
    if not client_id or not secret:
        sys.exit("Set SPOTIFY_CLIENT_ID and SPOTIFY_CLIENT_SECRET first.")
    basic = base64.b64encode(f"{client_id}:{secret}".encode()).decode()
    request = urllib.request.Request(
        "https://accounts.spotify.com/api/token",
        data=urllib.parse.urlencode({"grant_type": "client_credentials"}).encode(),
        headers={
            "Authorization": "Basic " + basic,
            "Content-Type": "application/x-www-form-urlencoded",
        },
    )
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)["access_token"]


def albums(access):
    """Every single and album, deduplicated by name (Spotify repeats releases)."""
    url = (
        f"https://api.spotify.com/v1/artists/{ARTIST_ID}/albums"
        "?include_groups=single,album&limit=50"
    )
    found = {}
    while url:
        page = get(url, access)
        for album in page["items"]:
            key = album["name"].strip().lower()
            kept = found.get(key)
            if not kept or album["release_date"] < kept["release_date"]:
                found[key] = album
        url = page.get("next")
    return list(found.values())


def embed(album, access):
    """A single plays as its one track; anything longer plays as the album."""
    if album["album_type"] == "single" and album["total_tracks"] == 1:
        tracks = get(
            f"https://api.spotify.com/v1/albums/{album['id']}/tracks?limit=1", access
        )
        if tracks["items"]:
            return "track/" + tracks["items"][0]["id"]
    return "album/" + album["id"]


def main():
    access = token()
    releases = []
    for album in albums(access):
        date = album["release_date"]
        if album["release_date_precision"] == "year":
            date += "-01-01"
        elif album["release_date_precision"] == "month":
            date += "-01"
        releases.append(
            {"title": album["name"], "date": date, "embed": embed(album, access)}
        )

    releases.sort(key=lambda release: release["date"], reverse=True)

    lines = [
        "  { title: %s, date: %s, embed: %s },"
        % (
            json.dumps(release["title"], ensure_ascii=False),
            json.dumps(release["date"]),
            json.dumps(release["embed"]),
        )
        for release in releases
    ]
    OUT.write_text(HEADER + "\n".join(lines) + "\n];\n", encoding="utf-8")
    print(f"Wrote {len(releases)} releases to {OUT}")


if __name__ == "__main__":
    main()
